name: responsi1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_responsi.png
  fonts:
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins-Black.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
